### ISSUE TITLE
Error spans are not marked red in Cloud Trace

### ISSUE THREAD

**Issue by vadeg** [GoogleCloudPlatform/opentelemetry-operations-java#214]
I am trying to integrate my application with [Cloud Trace](https://cloud.google.com/trace) to observe application traces. According to this [Cloud Trace doc](https://cloud.google.com/trace/docs/trace-overview#error_codes)

> Traces with error codes are colored red. When you select an error-code trace, the trace remains red in the scatterplot.

When I integrate my application using [this tutorial](https://cloud.google.com/trace/docs/setup/java-ot) with Cloud Trace via OpenTelemetry and send error spans to Cloud Trace I see that my error spans are marked with a blue do like normal spans: 
<img width="712" alt="error-span" src="https://user-images.githubusercontent.com/5587834/227365368-f2fa3516-6487-480b-a073-8f451af0f50d.png">

As you can see on the picture there are red dots which mean error spans. They come from GCP infrastructure and I don't have information how tracing is implemented there.

The details of the span:
<img width="734" alt="error-span-details" src="https://user-images.githubusercontent.com/5587834/227369720-5461024b-13b6-4822-84c1-90d453199750.png">

As you can see this span is the error span (`Status Code = 2`) what according to [this line of code in TraceTranslator](https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/blob/main/exporters/trace/src/main/java/com/google/cloud/opentelemetry/trace/TraceTranslator.java#L289) (which sets status code to 2 when there is an error span) means that the span is indeed the error span.

If I export the same span in Jaeger it marks span as an error span:
<img width="761" alt="jaeger-error-span" src="https://user-images.githubusercontent.com/5587834/227369361-ef60037f-808f-40d1-80f5-e0a22fc83858.png">

That means that from Opentelemetry and exporters PoV span metadata is correct. 

My question is _how to publish an error span using google exporter to enforce Cloud Trace to show it with a red dot in the scatterplot?_

**Comment by punya** [comment]
Thanks for the error report @vadeg.

This is a bug in the way that the Cloud Trace UI handles integer-valued (as opposed to string-valued) span attributes. The bug is limited to the scatterplot -- you'll notice that the Gantt chart view in the lower half of the screen correctly shows a red "error" icon on the relevant span.

We're working on a fix but I can't give you a timeline for how long it'll take.

As a workaround, you can use the OTel SDK to change the `http.status_code` attribute to a string `"500"`. Then the Cloud Trace exporter will set `/http/status_code` to the same value and you should see a red dot in the scatterplot.

**Comment by punya** [comment]
Hi @vadeg, this should now be fixed - please try again and let us know if the problem persists.

**Comment by vadeg** [comment]
@punya I've tested it and it works now. 
Thank you for your quick reply and support!
