### ISSUE TITLE
Support resource detection when using the java agent

### ISSUE THREAD

**Issue by dashpole** [GoogleCloudPlatform/opentelemetry-operations-java#278]
From https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/issues/247#issuecomment-1851432709:

> It seems that my current configuration is not enough to use the [Google Cloud official Resource Detectors](https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/blob/fed23bf5411a8420024633f57266b8ab616d8fee/detectors/resources/). Unlike [Auto-Configuration for OpenTelemetry in Google Cloud](https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/tree/fed23bf5411a8420024633f57266b8ab616d8fee/exporters/auto), Resource Detectors are not designed as extension for javaagent, so I cannot enable them via `otel.javaagent.extensions` system property.

**Comment by dashpole** [comment]
This might need to happen after https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/issues/266

**Comment by psx95** [comment]
Regarding [#247 (comment)](https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/issues/247#issuecomment-1851432709)

> As a trial, I enabled the [Auto-Configuration for OpenTelemetry in Google Cloud](https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/tree/fed23bf5411a8420024633f57266b8ab616d8fee/exporters/auto) as a javaagent extension, and it worked but metrics had no instance ID nor service ID in their attributes yet: generic_node{location:global,node_id:localhost,namespace:}


I did some investigation into this and here are my findings - 

### Summary
 - [Java Agent + Auto Exporter Setup](https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/tree/main/exporters/auto#autoinstrumentation-setup) works and I was able to view traces and metrics. 
   - Note 1: Shaded version of auto-exporter is needed when using it as an extension to Java Agent.
   - Note 2: Service name was not appearing as a metric attribute, but was being shown in trace attribute. This might be a bug which needs to be addressed. 
 - Google Cloud Resource Detectors are now bundled into the Java Agent as of [v2.2.0 Release](https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v2.2.0). Instructions to enable this can be found on [opentelemetry.io](https://opentelemetry.io/docs/languages/java/automatic/configuration/#enable-resource-providers-that-are-disabled-by-default).
   - Note: To export telemetry to Google Cloud, you would still need to use the Auto-exporter as an extension to the agent, regardless of enabling the gcp-resource-detector built-in to the agent.
 - For Java Agents v1.x.x, the resource detectors are not packaged in the Agent, however exporting to Google Cloud via the Agent still works when using the shaded auto-exporter since auto-exporter has the resource detectors built-in.


Is this in-line with your findings @[KengoDOTA](https://github.com/KengoTODA) ? 


@dashpole As part of this issue, I will look into why service name is not appearing in the metric attributes when using Java Agent.

**Comment by dashpole** [comment]
@psx95 I consider this issue fixed.  You are welcome to track the service.name attribute issue here, or in a new issue.

**Comment by psx95** [comment]
Created #313 to track this. Will mark this issue as completed.
