### ISSUE TITLE
XCloudTraceContextPropagator assumes lowercase header

### ISSUE THREAD

**Issue by mackenziestarr** [GoogleCloudPlatform/opentelemetry-operations-java#365]
`XCloudTraceContextPropagator` assumes the carrier parameter contains a lowercase header `x-cloud-trace-context` and as a result other valid capitalization styles of this header e.g. `X-Cloud-Trace-Context` are not extracted. This constraint makes the propagator class less flexible and I think there is benefit to allowing other common capitalizations of the header.  

https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/blob/72be92b5900080e7013ead9fb7f23bace3d84e86/propagators/gcp/src/main/java/com/google/cloud/opentelemetry/propagators/XCloudTraceContextPropagator.java#L93-L94

Proposed fix: support `X-Cloud-Trace-Context` in addition to the currently supported `x-cloud-trace-context` 
- when injecting the context, write both keys to the carrier 
- when extracting the context, lookup both keys in the carrier

this fix seems ideal from a performance perspective (vs. the suggested iterating over the keys and lowercasing them) but might have other implications

**Comment by dashpole** [comment]
Triage: IIRC, we do this for other languages, so we probably should here as well.

**Comment by dashpole** [comment]
I would have expected the carrier (e.g. http header implementation) to handle this.  We should check that first.

@mackenziestarr what were you trying to do when you encountered this?  Was it with OTel's HTTP library, or something else?

**Comment by mackenziestarr** [comment]
@dashpole in this case I'm integrating OTel into a thrift server that utilized a TCP transport so the "header" is passed in via a `map<string, string>` context field in the thrift request message - I can also change the clients to send a lowercase version and close this issue but i thought wider compatibility for different header capitalization styles might be desirable still because of the TODO in the source.

**Comment by psx95** [comment]
Hi @mackenziestarr,

I looked into this and I think the [TODO comment should have been removed/updated](https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/blob/72be92b5900080e7013ead9fb7f23bace3d84e86/propagators/gcp/src/main/java/com/google/cloud/opentelemetry/propagators/XCloudTraceContextPropagator.java#L93-L94). It is from a very old commit and I think spec might have changed since then - I searched around and found that the current spec around Get method mentions that [implementation of Get function is responsible for handling case sensitivity](https://opentelemetry.io/docs/specs/otel/context/api-propagators/#get).

Since we don't provide an implementation for `TextMapGetter`, I do not think this lowercasing should be addressed in these propagators. The users using this propagators should provide for an appropriate implementation for the getter method. For instance, we use the propagators in our e2e-tests and we provide a [TextMapGetter implementation that deals with case-sensitivity](https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/blob/72be92b5900080e7013ead9fb7f23bace3d84e86/e2e-test-server/src/main/java/com/google/cloud/opentelemetry/endtoend/ScenarioHandlerManager.java#L242).

Let me know if my interpretation of the spec makes sense to you.

**Comment by dashpole** [comment]
@psx95 should we open an issue upstream?

**Comment by psx95** [comment]
@dashpole an issue to update the propagators API spec or to somehow provide commonly used getters ?

**Comment by dashpole** [comment]
Sorry, I had forgotten context from https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/issues/365#issuecomment-2329708048.  @mackenziestarr when you implement your TextMapGetter, that is where the lowercasing should happen.

@psx95 you can close the issue once you've removed the comment.

**Comment by mackenziestarr** [comment]
@psx95 thanks the explanations and links to the spec, it wasn't very intuitive to me that one would need to iterate over entries in the map to test for the header key provided by `XCloudTraceContextPropagator`. 

i was hoping for an API that provided a default implementation of a `TextMapGetter` for `Map` so one could just call it like 
```java
Map<String, ?> input;
var context = new XCloudTraceContextPropagator(true).extract(Context.current(), input)
```

but understand if that is too specific to my own implementation

thanks for your time here @psx95 and @dashpole, we can call this closed
