### ISSUE TITLE
Feature: Fixed Attributes to include common/default env vars provided by GCP and Values set by User

### ISSUE THREAD

**Issue by AlexanderMann** [GoogleCloudPlatform/opentelemetry-operations-java#40]
# Motivation

In using auto exporting in production, we're seeing that a bunch of labels Cloud Trace expects to be present are just missing. We would like to be able to see:

- default common env vars populated as their respective labels
- certain env-vars/values passed in turned into labels

## Notes

This is the specific function/abstract method I'm referencing:

https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/blob/7cac7abd83372548da71a4a6fe463d90b167ffaf/exporters/trace/src/main/java/com/google/cloud/opentelemetry/trace/TraceConfiguration.java#L59

## Suggested Musical Pairing

https://soundcloud.com/michaelkiwanuka/money

**Comment by AlexanderMann** [comment]
@nilebox I'm hoping you all can provide some insight on _how_ this should be built out or whether I'm just even using this incorrectly 😅. Happy to do the leg work to put this feature in otherwise.

**Comment by zoercai** [comment]
Hi @AlexanderMann! There is currently no mapping of OpenTelemetry attributes to Cloud Trace attributes, which is why you're missing the labels.
The mapping also needs to be added to the metrics exporter for Cloud Monitoring, and since both have the same monitored resource attributes, it would be good to have both trace and metric use a common mapper.
Since there are a lot of attributes (https://cloud.google.com/monitoring/api/resources), I don't think we can add them all at once right now. I can make a skeleton for the common mapper with the basics, and you could add in any additional attributes you need, or I can review your PR if you want to implement the common mapper skeleton as well. Let me know which you'd prefer :)

**Comment by zoercai** [comment]
As for how it should be implemented, the equivalent Go repository has the [metrics exporter mapping implemented](https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/master/exporter/metric/metric.go#L317) already, so it would be something similar, with [these changes for the trace exporter](https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/pull/84/files)

**Comment by tomcham** [comment]
Hey @zoercai, any updates on having GCP attribute mappings like `opentelemetry-operations-go`? I'm using the metrics exporter and would really appreciate this feature.

**Comment by dashpole** [comment]
[Triage] I think this is still relevant (sorry this has sat for so long).  To confirm, you have resource attributes which you want to attach to all spans?

cc @aabmass 
This is related to discussions in other languages.
