### ISSUE TITLE
Feature Request: Cloudtrace exporter for java auto instrumentation needs an option to set a service name

### ISSUE THREAD

**Issue by dh-ger** [GoogleCloudPlatform/opentelemetry-operations-java#56]
When developing our spring boot application locally we enable the auto instrumentation and export this to Jaeger.
We really like the output it gives us, and the ability to show tracer per `servicename`.
What is involved in getting this to work is a property we set for the exporter.
`otel.exporter.jaeger.service.name`.

When we run in our UAT/Staging environments alongside the other microservices in our product we use the cloudtrace auto exporter.
(Found instructions from here https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/tree/master/exporters/auto)
However one piece of feedback we have is that it is hard to identify the traces that belong to our service, and we have struggled to find a reliable way to query for them.
What would be nice is a property like the jaeger exporter provides to set a property that we can then easily query by to get traces per service.

I understand we are early days for this, but something like this would help a lot in terms of the usability of cloudtrace.

Thanks

**Comment by aabmass** [comment]
@dh-ger not sure if you're still facing this issue, but I would recommend setting the [`service.name`](https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/issues/11) standard OTel resource attribute. I believe that will be added to all spans automatically.

Since this issue is so old, I'm going to close it out with this solution. Please reopen if you're still affected.
