### ISSUE TITLE
Auto jar isn't built with task assemble

### ISSUE THREAD

**Issue by tobias-** [GoogleCloudPlatform/opentelemetry-operations-java#65]
When I run `./gradlew assemble`, the auto-jar isn't produced. It seems this could be easily fixed by just changing `build` to `assemble` as per below.

```
diff --git a/exporters/auto/build.gradle b/exporters/auto/build.gradle
index 8007321..287d9aa 100644
--- a/exporters/auto/build.gradle
+++ b/exporters/auto/build.gradle
@@ -17,7 +17,7 @@ dependencies {
 
 jar.enabled = false
 
-tasks.build.dependsOn tasks.shadowJar
+tasks.assemble.dependsOn tasks.shadowJar
 
 shadowJar{
     classifier = null

```

**Comment by aabmass** [comment]
@psx95 will triage this

**Comment by psx95** [comment]
Hi @tobias- , is there a reason you are using `./gradlew assemble` instead of directly running `./gradlew shadowJar` ?

**Comment by tobias-** [comment]
> Hi @tobias- , is there a reason you are using `./gradlew assemble` instead of directly running `./gradlew shadowJar` ?

Not beyond that it's a gradle convention and I assumed that it would work the same as in "all" other projects.

**Comment by psx95** [comment]
Since this issue was opened a while ago, just to verify, the current behavior is - running `./gradlew assemble` does produce a JAR for `exporter-auto` - but this is not a shaded jar and I believe this is working as intended - *was assemble not producing a JAR at all ?*

The change you suggested would make the JAR generated from `assemble` to be the shaded one. Based on comments in #161 , we would want to generate both shaded and non-shaded variants of `exporter-auto` - so in this case, `assemble` should not depend on `shadowJar`.

**Comment by psx95** [comment]
Hi @tobias- did the previous comment clear things up?

**Comment by tobias-** [comment]
Like you said, it was opened a while ago. I assumed (without checking docs and perhaps erroneously) that `assemble` worked like `build` without tests and lint. Every project is if course allowed to configure their tasks in any way they please, so when I posted this issue (and frankly forgot about it afterwards) I thought it was just something that was overlooked, not something that was thought through.

I'm closing this as at its best, it's a nit pick issue, and at worst, just plain wrong.
